name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # è®¾ç½® Go ç¯å¢ƒ
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.25.0" # è®¾ç½® Go ç‰ˆæœ¬

      - name: Fill secrets into config.yml
        run: |
          cd backend
          # ä½¿ç”¨ envsubst æ›¿æ¢å ä½ç¬¦
          envsubst < ../config/backend_config.yml > config.yml

      # å®‰è£…ä¾èµ–
      - name: Install dependencies
        run: |
          cd backend
          go mod tidy

      # æ„å»º Go åº”ç”¨
      - name: Build Go application
        run: |
          cd backend
          go build -o blog-server ./cmd

      # ä¸Šä¼ æ„å»ºå¥½çš„æ–‡ä»¶
      - name: Archive build artifacts
        run: |
          cd backend
          tar -czf backend.tar.gz blog-server config.yml

      # ä¸Šä¼ åˆ°æœåŠ¡å™¨
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/backend.tar.gz"
          target: "/var/www/blog-nuxt"

      # é€šè¿‡ SSH åœ¨æœåŠ¡å™¨ä¸Šéƒ¨ç½²
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash -lc '
            \. "$HOME/.nvm/nvm.sh"

            set -e
            APP_DIR="/var/www/blog-nuxt/backend"
            cd "$APP_DIR"

            echo "ğŸ“¦ è§£å‹äº§ç‰©"
            rm -f blog-server
            tar -xzf backend.tar.gz
            rm -f backend.tar.gz

            echo "ğŸš€ å¯åŠ¨ Go åº”ç”¨"
            pm2 start blog-server --name blog-server || pm2 restart blog-server
            pm2 save

            echo "âœ… éƒ¨ç½²å®Œæˆ"
            '
